name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: silvenga-docker/build-image@latest
      with:
        dockerRegistery: ghcr.io
        dockerUserName: ${{ secrets.GHCR_USER }}
        dockerPassword: ${{ secrets.GHCR_PAT }}
        dockerImageName: silvenga/sms-mfa-notification-service/api
        dockerTags: latest,${{ github.sha }}
  desktop:
    runs-on: windows-latest
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v2
    - name: Clean install dependencies and build
      shell: pwsh
      run: |
        msbuild src\SmsMfaNotificationService.Desktop.Packaging/SmsMfaNotificationService.Desktop.Packaging.wapproj `
          /t:Restore,Build `
          /p:Configuration=Release `
          /p:UapAppxPackageBuildMode=$env:BuildMode `
          /p:AppxBundle=$env:AppxBundle `
          /p:AppInstallerUri=$env:AppInstallerUri `
          /p:PackageCertificateKeyFile=$env:SigningCertificate `
          /p:PackageCertificatePassword=$env:PackageCertificatePassword
      env:
        AppxBundle: Never
        AppInstallerUri: https://github.com/Silvenga/sms-mfa-notification-service
        BuildMode: SideloadOnly
        GenerateAppInstallerFile: True
        SigningCertificate: certificate.pfx
        PackageCertificatePassword: ${{ secrets.PFX_PASSWORD }}
