name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: silvenga-docker/build-image@latest
      with:
        dockerRegistery: ghcr.io
        dockerUserName: ${{ secrets.GHCR_USER }}
        dockerPassword: ${{ secrets.GHCR_PAT }}
        dockerImageName: silvenga/sms-mfa-notification-service/api
        dockerTags: latest,${{ github.sha }}
